# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c936a25d64e61dfddb074bceef203180daad6db6bd7bee0479b18719c4c3b32fb0937d7e22ce2333850fe869a8b4f208887426035aa7ad0293dd0157a84affc4

test:
  secret_key_base: fd628d14d8def087cc2a6a83ffe118b8797ae38173ecbeed732622b8194be24ec9b2eded039be6c148705b61a326e7c085cca5c79fc3d1431034f9657cd937d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
